# !/usr/bin/env python3

#!/usr/bin/env python3

# Main.py file generated by New Project wizard

# Created:   Sun Dec 3 2023
# Processor: RPI4
# Compiler:  Python 3 (Proteus)

# Modules
from goto import *
import time
import var
import pio
import resource

# Peripheral Configuration Code (do not edit)
#---CONFIG_BEGIN---
import cpu
import FileStore
import VFP

def peripheral_setup () :
# Peripheral Constructors
 pio.cpu=cpu.CPU ()
 pio.storage=FileStore.FileStore ()
 pio.server=VFP.VfpServer ()
 pio.storage.begin ()
 pio.server.begin (0)
# Install interrupt handlers

def peripheral_loop () :
 pio.server.poll ()

#---CONFIG_END---

# Main function
def main () :
# Setup
 peripheral_setup()
# Infinite loop
 while 1 :
  peripheral_loop()
  pass
# Command line execution
if __name__ == '__main__' :
   main()
